apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

# Prod stays on the stable version
images:
  - name: demo-app
    newTag: 1.0.0

patches:
  - target:
      kind: Ingress
      name: demo-app
    patch: |
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: demo-app
      spec:
        rules:
          - host: prod-demo.local
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: demo-app
                      port:
                        number: 80