apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: demo-app-networkpolicy
spec:
  podSelector:
    matchLabels:
      app: demo-app
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx
  policyTypes:
    - Ingress
