---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: demo-api-key
spec:
  encryptedData:
    API_KEY: AgDZg+AjVgM5MP6e9ak6bGaQKGtty/Ol5RUy1nTmOo88CgecgwWuo+3+R92qyoBNMxR6dv4Dv5FhHmGtliNUWsdvlSbB9ymdxqWmDx6WQq6wbBoaZ890yTSwQn8kiOMYYQspVAD1wBWWuTcfcCrhzZBm0sKSPBJdoXfUzHdca3dNIU+I+yC5rimU913i1zb4aNWSxL5ae8k4M6uxJzU1byiOM2Lr4uBpnxhKBri3T3xPbTNn8TAVQbDxMmcANM7bKKamRl1Mr2fDmhoLaCDt7KFAAKu8A6uA3kY6rtG1cjrPq8EiNb1nasAN7AZ62eoF60yU/dOauzx+VL4HSnQly/emrJkyiyh3hCej995xuFdWwgiQq30prTiHsEkxZBgvnJp9ZilB7vHBAh4yFjBf2N4qyWlpS853wSf++Yhc06pNYnjc2yrbcgubBdWo9+XtzCD3SK8LXft5shgwKFjF41/JpBxsvy6sPSVZbq7YmrQFc9QDW7b71I/ZaPdTZL4pxd+K1fX6R/vxYoiQdLADukvKaVajvV1YptMtpqBQbGzcA/BSScZBfZbObFlArCJNKmQparKMx1xjj8Pxi65D+Vff/499N2Tirq4uQm7+/1nLhs3qCArDR8JC4h6K4QkWrDzCadgWpeqJGA9A2uqTgH31QHiLObbkSlx91Nb+ACeyfLlJjkG4CuEF5GS5PW08fbXRYn3rYTdFipPGytPECWcDsuo=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: demo-api-key
