apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-credentials
  namespace: default
spec:
  encryptedData:
    password: AgBy3...sampleEncryptedBase64Payload...
  template:
    metadata:
      name: db-credentials
    type: Opaque
